# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: ""
url: "https://xxxcrel.github.io"
date_format: "ordinal"
title: 克里尔
subtitle: "Code Monkey"
description: "克里尔的个人博客"
lang: zh-CN
timezone: Asia/Shanghai
encoding: "utf-8"
logo: "https://github.com/xxxcrel.png?size=320"

# ---------------- #
#      Author      #
# ---------------- #
author:
    name: Xuecheng Wu
    url: https://github.com/xxxcrel
github_username: xxxcrel
location:  China
email: xxxcrel@gmail.com
social:
    name: Xuecheng Wu
    links:
        - https://github.com/xxxcrel
        - https://www.weibo.com/3919936481/profile
        - https://www.zhihu.com/people/j-devi

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    auto_ids: true
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: false
        span:
            line_numbers: false
highlighter: rouge
paginate: 10
paginate_path: "/page:num/"
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
    - jemoji
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: xxxcrel/xxxcrel.github.io
